[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Guide"
  pageRef = "/tags/guide/"
  weight = 20
[[main]]
  name = "Linux"
  pageRef = "/tags/linux"
  weight = 30
[[main]]
  name = "Web DEV"
  pageRef = "/tags/web-dev"
  weight = 40
[[main]]
  name = "Tutti"
  pageRef = "/tags"
  weight = 50

[[social]]
  name = "YouTube"
  pre = "fab youtube"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/thetuxdev"
  weight = 20

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  pageRef = "/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation